spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://127.0.0.1:3306/Leaflet?serverTimezone=GMT%2B8&characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
  jackson:
    default-property-inclusion: non_null
  redis:
    host: 192.168.1.169
    port: 6379

server:
  servlet:
    context-path: /scut






  #logging:
 #pattern:
 #   console: "%d - %msg%n"
# path: D:/test1/
 #file: D:/test1/sell.log
  port: 8081
#  level:
#日志级别可以精确盗垒
#    com.imooc.LoggerTest: debug

wechat:
 appId: qwewqew
 appSecret: wqeqw


